### ISSUE TITLE
QGIS - Build RORB

### ISSUE THREAD

**Issue by water-qgis** [norman-tom/pyromb#10]
After obtaining a .catg file from "Build RORB" in QGIS, I noticed that the areas of the subareas from the .catg file and the shp file, don't match. This is the same problem for the example files provided for Build RORB (QGIS). Why is this the case?

**Comment by norman-tom** [comment]
Sounds like you have an answer, but I believe RORB has an optimization step when saving the control file, so they end up different. Please confirm if that's not the case.
