### ISSUE TITLE
Can't find Runoff Model: RORB plugin on plugin manager

### ISSUE THREAD

**Issue by Global-Citizen** [norman-tom/pyromb#4]
Hi Tom, I tried to use this cool tool but got stuck on finding the runoff model plugin. Has it been published yet?

**Comment by norman-tom** [comment]
Still working on getting this on the official QGIS plugin repo, apologies.  Check out the repo https://github.com/norman-tom/runoff-model, This is the QGIS plugin which you can install manually to QGIS, just copy the "builder-rorb" folder to the QGIS plugin location. It is a process plugin so it will be under the processing toolbar as "Runoff Model".

If not I can let you know when the plugin is uploaded to the official QGIS repository, hopefully not too long.

**Comment by Global-Citizen** [comment]
Hey Tom, thanks for the update. I just gave it a go, and it's working perfectly. You're a genius!!!

**Comment by norman-tom** [comment]
Runoff Model: RORB is now available on the QGIS repo.
