### ISSUE TITLE
RORB model upside down and name issue

### ISSUE THREAD

**Issue by Global-Citizen** [norman-tom/pyromb#5]
Hi Tom,
I tried to use my own files, but got some issues as title said. Could you please take a look?
The files are: https://github.com/Global-Citizen/runoff-model-test-file

**Comment by norman-tom** [comment]
The model is upside down within the RORB GE only, the .cat files do not contain the graphical information required to display the catchment in the RORB GE correctly.  

The sub-basin names again are a graphical things, not necessary to actually run the model, so they are not included in the .cat files. 

I can confirm that the catchment appears to be built correctly. 

![rorb_ge](https://github.com/norman-tom/pyromb/assets/39142955/71c4bcd7-ae82-43ec-8cc4-bba65a27f90a)
![catchment_built](https://github.com/norman-tom/pyromb/assets/39142955/d3e9bbdb-6fa3-41da-877d-cf53b50a2e77)

**Comment by Global-Citizen** [comment]
Hi Tom, thank you for the response. You are right. This plugin is amazing. I struggled with an unknown error by using MiRORB, your plugin just saved my life. Can't wait for the further updating (update data links, support other reach types).
