### ISSUE TITLE
GE support feature doesn't work well for v0.2.0

### ISSUE THREAD

**Issue by Global-Citizen** [norman-tom/pyromb#6]
Hi Tom, 

Just tested the plugin, but GE support feature doesn't work for me. The pyromb version has updated to 0.2, but it seems an error occurred: 
`A:\QGIS 3.28.5>pip install --upgrade pyromb
Requirement already satisfied: pyromb in a:\qgis 3.28.5\apps\python39\lib\site-packages (0.1.0)
Collecting pyromb
  Downloading pyromb-0.2.0-py3-none-any.whl.metadata (6.2 kB)
Downloading pyromb-0.2.0-py3-none-any.whl (25 kB)
Installing collected packages: pyromb
  Attempting uninstall: pyromb
    Found existing installation: pyromb 0.1.0
    Uninstalling pyromb-0.1.0:
      Successfully uninstalled pyromb-0.1.0
Successfully installed pyromb-0.2.0
WARNING: There was an error checking the latest version of pip.`  

Not sure if it is the reason. 
Thanks for your effort. I appreciate it. 

Regard,
Theo

**Comment by norman-tom** [comment]
Does the plugin fail within QGIS? This may be because the version of pip shipped with qgis is older, if so that shouldn't be an issue.

**Comment by Global-Citizen** [comment]
> Does the plugin fail within QGIS? This may be because the version of pip shipped with qgis is older, if so that shouldn't be an issue.

Hi Tom, I have tried to update the pip with the latest version but still got same issue. I just tried it on my office computer with the same version of qgis and pip, and it works. I will try to figure out the issue of my pc tonight and let you know how it goes. Thanks. Theo

**Comment by norman-tom** [comment]
Seems to be an issue with pip. Please let me know if you still can't get it working.
