### ISSUE TITLE
Can not install Plugin RORB Plugin

### ISSUE THREAD

**Issue by ChamathAkalankancbc** [norman-tom/pyromb#8]
Hi Norman,

Thank you for developing plugin for RORB. However when I try to install the plugin, it gives the following error. Could you please help me to fix this. I am using QGIS version 3.22.4

![image](https://github.com/norman-tom/pyromb/assets/152950706/5dc855c2-2399-4846-997e-bcbcacaadda9)
![Capture](https://github.com/norman-tom/pyromb/assets/152950706/29ad2deb-7075-4860-9813-93dd0db01002)

Thank you and appreciate your help

**Comment by norman-tom** [comment]
Hi,

the issues is that you need to install the Pyromb library to the QGIS environment. Ill put the instructions below but it is detailed on the Pyromb homepage https://github.com/norman-tom/pyromb
 __________________________________________________________________________________________________________________________
Installing for the QGIS Runoff Model Builder plugin:
For MacOS or Linux, QGIS does not have its own python environment so PR can be installed through pip directly from the terminal by using the command above.

For Windows, QGIS has its own python environment. To install PR to work with QGIS, it needs to be installed via the OSGeo4W shell. Two methods depending on your version of QGIS, for newer versions,

Option 1.
Open the OSGeo4W Shell (may need admin permission)
Install via pip
$ pip install pyromb
If that fails, try:

Option 2.
Open the OSGeo4W Shell (may need admin permission)
Enter py3_env
Install via pip
$ python -m pip install pyromb

**Comment by ChamathAkalankancbc** [comment]
Working very well!!

Thank you very much sir
